### ISSUE TITLE
Blastn 

### ISSUE THREAD

**Issue by zebasilio** [asan-nasa/adapt_find#1]
Hi!

I have created a conda environment where I installed the packages to use with adapt_find.py
Although I have installed blast version 2.10, and this version is in the PATH, it says I should have blast 2.7 or higher. 
how can I solve this issue?
Thank you.
With best regards 
José

**Comment by asan-nasa** [comment]
Hello Jose,

Thanks for pointing that out. I have made the necessary changes. Please download the latest version of the PYTHON script and see if it works. Now the script should work fine. But if you experience any difficulties, please let me know.

**Comment by zebasilio** [comment]
Hi!

Thanks for the fast reply. I still have some issues. now the error message is following:

Traceback (most recent call last):
  File "adapt_find.py", line 105, in <module>
    elif (ver < 7.0):
TypeError: '<' not supported between instances of 'str' and 'float'

Thanks for the help.
Best, José

**Comment by asan-nasa** [comment]
Hello Jose,

It is fixed now. I initially tested the code  on PYTHON 2.7. Apparently it runs without any problem on PYTHON 2.7, but not with PYTHON 3. In PYTHON3, it throws the same error message as you quoted. But now i fixed it and tested with PYTHON3 and it works fine. I have amended the changes in the script available in github. Please let me know if the updated script works

**Comment by zebasilio** [comment]
Hi Asan-Nasa,

Thank you, it works. I some further questions:

1. is it possible to work with fastq.gz files?
2. is it possible to only find the adapter sequence without trimming?
3. is it possible to change the argument values of cutadapt?
Thank you.
Best wishes, José

**Comment by asan-nasa** [comment]
Hi,

Sorry for the late reply because of the holiday season.

Answers below:
1) It is possible to work with fastq.gz
2) there is no separate mode to find the adapter sequence without trimming. The trimming step acts as a quality control as it also reports the number of raw reads with the predicted adapter sequence
3) yes it is possible to change the argument values in cutadapt using --min_len and --max_len

I am making changes to the script for the output path issue. Will update the script tomorrow.
